import sys
import json
import time

# Get video path from Node
video_path = sys.argv[1]

# Simulate AI processing
time.sleep(2)

result = {
    "transcript": "This is a dummy transcript generated by AI.",
    "highlights": [
        {"start": 5, "end": 15},
        {"start": 30, "end": 45}
    ],
    "hashtags": ["#ai", "#video", "#viral"],
    "score": 8.5
}

# Print JSON so Node can read it
print(json.dumps(result))